name: Tests

on: [push]

jobs:
  test:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
        pip install pytest
    - name: Test with pytest
      run: pytest -v
