name: Tests

on: [push]

jobs:
  test:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
        pip install flake8
        pip install codecov
        pip install pytest-cov
    - name: Check all dependeccies
      run: pip list
    - name: Test with pytest
      # run: pytest -vs
      run: python -m pytest tests -vs
    - name: Test with flake8
      run: flake8 src
    - name: Test with codecov
      run:
        pytest --cov=./ --cov-report=xml
        codecov
